### ISSUE TITLE
Memory Alignment Issue on ARM is causing a wrong ip package

### ISSUE THREAD

**Issue by redbrain17** [fredbcode/Vrrpd#10]
we observed a strange alignment issue in vrrpd_build_pkt when we build vrrpd for the ARM architecture. The ip addresses are placed wrong in the created ip packet, like this:

virtual-router ethernet0/1 1 priority 255 ip 192.168.100.1
  /usr/sbin/vrrpd -F -i eth1.2 -v 1 -p 100 -d 1 192.168.100.1

    100.1.224.0 > 0.18.0.0: vrrp 100.1.224.0 > 0.18.0.0: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20, (bad vrrp cksum 5652), addrs: 100.1.0.0
	    0x0000:  0100 5e00 0012 0000 5e00 0101 0800 4500
	    0x0010:  0028 1800 0000 ff70 9ea9 6401 e000 0012
	    0x0020:  0000 2101 6401 0001 5652 6401 0000 0000
	    0x0030:  0000 0000 0000

if we compile it for x86 architecture everything is fine and Ip package looks like this:

     192.168.100.1 > 224.0.0.18: vrrp 192.168.100.1 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 255, authtype none, intvl 1s, length 20, addrs: 192.168.100.1
            0x0000:  0100 5e00 0012 0000 5e00 0101 0800 4500
	        0x0010:  0028 0b4a 0000 ff70 ab5f c0a8 6401 e000
	        0x0020:  0012 2101 ff01 0001 bb51 c0a8 6401 0000
	        0x0030:  0000 0000 0000 0000 0000 0000

this is caused by some memory alignment on ARM with the IP buffer (struct)
If  the -Wcast-align option from the Compiler is enabled  the ARM compiler warns about this in original code.

vrrpd.c:539:18: warning: cast increases required alignment of target type [-Wcast-align]
vrrpd.c: In function 'vrrp_build_ip':
vrrpd.c:653:22: warning: cast increases required alignment of target type [-Wcast-align]
vrrpd.c: In function 'vrrp_build_vrrp':

**Comment by fredbcode** [comment]
Yes, there is something wrong I should take a look

Otherwise:

priority 255 ip 192.168.100.1
/usr/sbin/vrrpd **-F** -i eth1.2 -v 1 **-p 100** -d 1 192.168.100.1

-d 1 -> pointless (1 is the default value)

-F ? priority 255 ? Which version exactly are you using (vrrpd -v) ?

Another thing strange:

With vrrpd -F -i eth1.2 -v 1 -p 100 -d 1 192.168.100.1

192.168.100.1 > 224.0.0.18 the packet is from the VIP to the multicast ? It should be from the physical address eth1.2 

Caution VIP != Physical address  

eg:
eth1.2 -> 192.168.100.2 -> or whatever you want, like 10.1.1.1 no matter 
VIP -> 192.168.100.1

**Comment by redbrain17** [comment]
Sorry, the -F option I introduced myself to run vrrpd in foreground not in
background (I make the fork() depending on that -F flag).

**Comment by redbrain17** [comment]
I use vrrpd in Version 1.13  + a patch to compile it for ARM + patch to run
vrrpd in Foreground

**Comment by fredbcode** [comment]
Can you make a re-try now (with a conf fixed I mean) ?

**Comment by redbrain17** [comment]
this is still an issue, but only on our arm platform. On normal x86 with ubuntu it works like expected.

**Comment by fredbcode** [comment]
Tried with raspbian (wheezy), the problem seems not related with ARM
Which distribution are you using ? 

ifconfig

eth0      Link encap:Ethernet  HWaddr b8:27:eb:6e:4f:b5  
          inet addr:192.168.0.100  Bcast:192.168.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1886 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1749 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1178735 (1.1 MiB)  TX bytes:186392 (182.0 KiB)

 ./vrrpd -i eth0 -n -v 1 10.1.1.1

08:49:47.947755 IP 192.168.0.100 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20
08:49:48.987739 IP 192.168.0.100 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20
08:49:50.027715 IP 192.168.0.100 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20
08:49:51.057694 IP 192.168.0.100 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20
08:49:52.087685 IP 192.168.0.100 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20
08:49:53.117646 IP 192.168.0.100 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20
08:49:54.147647 IP 192.168.0.100 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20
08:49:55.177641 IP 192.168.0.100 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20
08:49:56.207634 IP 192.168.0.100 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20
08:49:57.237629 IP 192.168.0.100 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20
08:49:58.277622 IP 192.168.0.100 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20
08:49:59.307642 IP 192.168.0.100 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20
08:50:00.337623 IP 192.168.0.100 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20
08:50:01.367646 IP 192.168.0.100 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20
08:50:02.407703 IP 192.168.0.100 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20
08:50:03.437704 IP 192.168.0.100 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20
08:50:04.477711 IP 192.168.0.100 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20
08:50:05.517696 IP 192.168.0.100 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20
08:50:06.547691 IP 192.168.0.100 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20
08:50:07.577699 IP 192.168.0.100 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20
08:50:08.607691 IP 192.168.0.100 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20
08:50:09.637672 IP 192.168.0.100 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20
08:50:10.677667 IP 192.168.0.100 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 100, authtype none, intvl 1s, length 20

/etc/apt/sources.list
deb http://mirrordirector.raspbian.org/raspbian/ wheezy main contrib non-free rpi

1.13 from git without any modification

**Comment by fredbcode** [comment]
Ok, can't reproduce with PI2 (ARM) here
Please feel free to reopen this bug if you can provide new informations
